---

- name: Generate epoch time
  set_fact:
    addvol: "{{ volume }}_{{ ansible_date_time.epoch }}"
  run_once: True

- name: Create additional logical volume.
  lvol:
    lv: "{{ addvol }}"
    thinpool: "{{ glusterfs_poolname }}"
    size: "{{ addsize }}g"
    vg: "{{ glusterfs_vgname }}"

- name: Format the added volume
  filesystem:
    dev: "/dev/{{ glusterfs_vgname }}/{{ addvol }}"
    fstype: xfs
    opts: "-i size=512 -n size=8192"

- name: Mount added volume
  mount:
    name: "/gluster/{{ addvol }}"
    src: "/dev/{{ glusterfs_vgname }}/{{ addvol }}"
    fstype: xfs
    opts: "defaults,inode64,noatime"
    state: mounted

- name: Create brick folder
  file:
    path: "/gluster/{{ addvol }}/export"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set correct label on bricks
  sefcontext:
    path: "/gluster/{{ addvol }}'(/.*)?'"
    setype: glusterd_brick_t
    state: present
    reload: yes

- name: make brick name
  set_fact:
    brick: "{% for i in ansible_play_hosts%}\
             {{ i }}:/gluster/{{ addvol }}/export \
            {% endfor %}"

- name: Add the newly made bricks to the gluster volume
  shell: gluster volume add-brick {{ volume }} replica {{ glusterfs_replicas }} arbiter 1 {{ brick  }} --mode=script
  run_once: True

- name: When a volume is extended, start a rebalance operation
  shell: gluster volume rebalance {{ volume }} start --mode=script
  run_once: True
