---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "8"

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
